require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1

# would like to re-enable
# https://github.com/nevir/rubocop-rspec/issues/62
RSpec/FilePath:
  Enabled: false

Metrics/MethodLength:
  Max: 48

Metrics/AbcSize:
  Max: 51

Metrics/PerceivedComplexity:
  Max: 10

Style/RegexpLiteral:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

# default disabled rules
Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - scrum_lint.gemspec
    - spec/**/*_spec.rb

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: true

# non-conventional rules
Style/LambdaCall:
  EnforcedStyle: braces

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/DescribeMethod:
  Exclude:
    - spec/scrum_lint/version_spec.rb
